version: "3.7"
services:
  api_service:
    container_name: teams_api
    build: ./app
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:4.4.3"
    container_name: teams_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./.data/mongo:/data/db